main: io.github.vehsamrak.minecraft.gradle.Main
name: TestPlugin
version: 1.0-SNAPSHOT
description: Test bukkit plugin
load: STARTUP

commands:
  test:
    description: Run tests.
    aliases: [check]
    usage: Syntax error! Use "/<command>" to run tests.
